[package]
name = "Fortunes-Favourate"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.14", default-features = false, features = ["bevy_winit", "bevy_ui", "png"] }
rand = "0.8"